name: CVCommandGateway
main: org.cubeville.cvcommandgateway.CVCommandGateway
authors: [FrediW]
version: 1.20
api-version: 1.20

depends: [CVTools]

commands:
  cmdtestxxxxx:
    description: Test
    permission: cvcommandgateway.test
